AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mtw-permanents-table

  SAM Template for the static DynamoDB storage and Cognito pool associated with MakeTheWorld.

Parameters:
  TablePrefix:
    Type: String
    Default: 'mtw'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

  AppID:
    Type: String
    Description: (Required) The application ID of the installing Amplify app.
    MinLength: 3
    MaxLength: 50
    ConstraintDescription: 'Required.'

  CognitoCallbackURL:
    Type: String
    Default: 'http://localhost:3000'
    Description: (Required) The URL that Cognito should return control to, after authorizing a user.

Resources:
    PermanentsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            - AttributeName: "PermanentId"
              AttributeType: "S"
            - AttributeName: "DataCategory"
              AttributeType: "S"
          BillingMode: "PAY_PER_REQUEST"
          KeySchema:
            - AttributeName: "PermanentId"
              KeyType: "HASH"
            - AttributeName: "DataCategory"
              KeyType: "RANGE"
          GlobalSecondaryIndexes:
            - IndexName: DataCategoryIndex
              KeySchema:
                - AttributeName: DataCategory
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
          TableName: !Sub '${TablePrefix}_permanents'
    StorageBucket:
        Type: AWS::S3::Bucket
    UserPool:
      Type: AWS::Cognito::UserPool
      UpdateReplacePolicy: Retain
      Properties:
        UserPoolName: !Sub ${TablePrefix}-user-UserPool
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: "OFF"
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        EmailVerificationSubject: Welcome to Make The World
        EmailVerificationMessage: >
            Thank you for signing up for Make The World.  Here is your verification code (the system will ask for it): {####}
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireUppercase: false
            RequireNumbers: false
            RequireSymbols: false
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: !Sub ${TablePrefix}-client
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
        CallbackURLs:
          - !Ref CognitoCallbackURL
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId: !Ref UserPool
        Domain: !Sub ${TablePrefix}-${AppID}-auth

Outputs:
    TablePrefix:
        Description: The prefix with which tables should begin.
        Value: !Sub ${TablePrefix}
        Export:
            Name: !Sub "${AWS::StackName}-TablePrefix"

    StorageBucket:
        Description: The S3 bucket for internal system object storage
        Value: !Ref StorageBucket
        Export:
          Name: !Sub "${AWS::StackName}-StorageBucket"

    UserPoolClient:
        Description: The client ID for the player user pool
        Value: !Ref UserPoolClient
        Export:
          Name: !Sub "${AWS::StackName}-UserPoolClient"

    UserPoolId:
        Description: The internal ID for the player user pool
        Value: !Ref UserPool
        Export:
          Name: !Sub "${AWS::StackName}-UserPoolId"
